[project]
name = "mingrad"
version = "0.1.0"
description = "A minimal autograd implementation in pure python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "graphviz>=0.20.3",
    "ipykernel>=6.29.5",
]
